module.exports = {
  EX1: {
    id: "EX1",
    status: "400",
    message: "Email field is not Provided",
    meta: "",
    context: "User",
  },
  EX2: {
    id: "EX2",
    status: "400",
    message: "Password field is not Provided",
    meta: "",
    context: "User",
  },
  EX3: {
    id: "EX3",
    status: "400",
    message: "Password field is not Provided",
    meta: "",
    context: "User",
  },
  EX4: {
    id: "EX4",
    status: "400",
    message: "User with this Email Adress Already Exists",
    meta: "",
    context: "User",
  },
  EX5: {
    id: "EX5",
    status: "400",
    message: "Something Went Wrong",
    meta: "",
    context: "General",
  },
  EX6: {
    id: "EX6",
    status: "400",
    message: "Cannot find any User with such an Email",
    meta: "",
    context: "User",
  },
  EX7: {
    id: "EX7",
    status: "400",
    message: "Invalid Password or Username",
    meta: "",
    context: "User",
  },
  EX8: {
    id: "EX8",
    status: "400",
    message: "Please provide a userName",
    meta: "",
    context: "User",
  },
  EX9: {
    id: "EX9",
    status: "400",
    message: "Authrization failed",
    meta: "",
    context: "User",
  },
  EX10: {
    id: "EX10",
    status: "400",
    message: "Something went wrong",
    meta: "",
    context: "General Exception",
  },
  EX11: {
    id: "EX11",
    status: "400",
    message: "Title is missing",
    meta: "",
    context: "TODO",
  },
  EX12: {
    id: "EX12",
    status: "400",
    message: "Please provide a todo ID",
    meta: "",
    context: "TODO",
  },
};
